apiVersion: apps/v1
kind: Deployment
metadata:
  name: msorderservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msorderservice 
  template:
    metadata:
      labels:
        app: msorderservice
    spec:
      containers:
        - name: msorderservice
          image: mreas/msorderservice
---
apiVersion: v1
kind: Service
metadata:
  name: msorderservice-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: msorderservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: msorderservice