apiVersion: v1
kind: Service
metadata:
  name: msorderservice-np-srv
spec:
  type: NodePort
  selector:
    app: msorderservice
  ports:
    - name: msorderservice 
      port: 80
      targetPort: 8080
      protocol: TCP